[package]
name = "qevy_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
bevy_xpbd_3d = "0.3.1"
qevy = { path = "..", features = ["xpbd"] }
